### ISSUE TITLE
ipv4 is shown in tracker also when ipv6 was specified during setup

### ISSUE THREAD

**Issue by asbachb** [ZencashOfficial/secnodetracker#25]
### Problem
When a machine has a dual stack configuration (ipv4 & ipv6). Always the ipv4 address is shown on tracker website.
This is caused since nodejs always resolve ipv4 dns before if not specified otherwise.

### Solution
Since socket-io seems to be not configurable which dns should be used the dns needs to be resolved before connecting the socket. In order to get the right ip from dns the during the setup specified "ipv" property needs to be passed to dns request.

**Comment by num81** [comment]
The current work around for this issue is to put the ipv6 addresses into the nodes hosts file.

2400:cb00:2048:1::681b:250 ts1.eu.zensystem.io
2400:cb00:2048:1::681b:350 ts1.eu.zensystem.io
2400:cb00:2048:1::681b:250 ts1.na.zensystem.io
2400:cb00:2048:1::681b:350 ts1.na.zensystem.io
2400:cb00:2048:1::681b:250 ts1.sea.zensystem.io
2400:cb00:2048:1::681b:350 ts1.sea.zensystem.io

This forces the node to preference the ipv6 connection.

**Comment by asbachb** [comment]
https://github.com/nodejs/node/pull/14731

**Comment by asbachb** [comment]
I had a little discussion with some nice guy on node.js irc. We found out that node.js is not following the ipv6 RFC which describe that applications should return ipv6 addresses first.
node.js internally resort the addresses to show ipv4 first.

There's a PR to provide a flag to switch to an RFC compliant behaviour: https://github.com/nodejs/node/pull/17793
